export const PERMISSIONS = {
    USER_VIEW: 'USER_VIEW',
    USER_CREATE: 'USER_CREATE',
    USER_UPDATE: 'USER_UPDATE',
    USER_DELETE: 'USER_DELETE',
    USER_PERMISSION_VIEW: 'USER_PERMISSION_VIEW',
    USER_PERMISSION_ASSIGN: 'USER_PERMISSION_ASSIGN',
    USER_PERMISSION_REMOVE: 'USER_PERMISSION_REMOVE',
    
    ROLE_VIEW: 'ROLE_VIEW',
    ROLE_CREATE: 'ROLE_CREATE',
    ROLE_UPDATE: 'ROLE_UPDATE',
    ROLE_DELETE: 'ROLE_DELETE',
    ROLE_PERMISSION_VIEW: 'ROLE_PERMISSION_VIEW',
    ROLE_PERMISSION_ASSIGN: 'ROLE_PERMISSION_ASSIGN',
    ROLE_PERMISSION_REMOVE: 'ROLE_PERMISSION_REMOVE',

    PERMISSION_VIEW: 'PERMISSION_VIEW',

    AUDIT_VIEW: 'AUDIT_VIEW'
};