-- Clean up existing objects if they exist to allow clean runs
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE test_users CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- Create Table
CREATE TABLE test_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
/

-- 1. Procedure: add_user
-- Takes IN parameters (username, email) and returns the generated ID via OUT parameter
CREATE OR REPLACE PROCEDURE add_user (
    p_username IN VARCHAR2,
    p_email IN VARCHAR2,
    p_id OUT NUMBER
) AS
BEGIN
    INSERT INTO test_users (username, email)
    VALUES (p_username, p_email)
    RETURNING id INTO p_id;
END;
/

-- 2. Procedure: get_user_by_id
-- Takes IN parameter (id) and returns username and email via OUT parameters
CREATE OR REPLACE PROCEDURE get_user_by_id (
    p_id IN NUMBER,
    p_username OUT VARCHAR2,
    p_email OUT VARCHAR2
) AS
BEGIN
    SELECT username, email INTO p_username, p_email
    FROM test_users
    WHERE id = p_id;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_username := NULL;
        p_email := NULL;
END;
/

-- 3. Function: get_total_users
-- Returns the total count of users in the table (returns NUMBER)
CREATE OR REPLACE FUNCTION get_total_users
RETURN NUMBER AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM test_users;
    RETURN v_count;
END;
/

-- 4. Function: concat_user_info
-- Takes IN parameter (id) and returns a formatted string containing user info (returns VARCHAR2)
CREATE OR REPLACE FUNCTION concat_user_info (
    p_id IN NUMBER
) RETURN VARCHAR2 AS
    v_username VARCHAR2(50);
    v_email VARCHAR2(100);
BEGIN
    SELECT username, email INTO v_username, v_email
    FROM test_users
    WHERE id = p_id;
    RETURN 'User: ' || v_username || ' <' || v_email || '>';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'User with ID ' || p_id || ' not found';
END;
/
